### ISSUE TITLE
Document comment restrictions inside .respond-to mixins

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-core#15]
TIL that you cannot use traditional CSS `/* ... */` comments inside the statement block of our `.respond-to` mixins. Less will not compile, giving the following error:

``` sh
>> ParseError: unmatched `/*`
```

Additionally, you cannot comment out **a single, unmatched curly brace** inside the `.respond-to` statement block. Less will get to the end of the document and think that there is an unmatched curly brace missing its partner.

These quirks should be documented alongside the `.respond-to` mixins.

**Comment by himedlooff** [comment]
Might be related: https://github.com/less/less.js/issues/2032
