### ISSUE TITLE
max-width on paragraphs

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-core#25]
We should set a max-width on headings to keep line lengths readable.

**Comment by Scotchester** [comment]
We have headings long enough to be a concern?

**Comment by himedlooff** [comment]
Consider this:

``` html
<p class="h3">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque saepe at ut quo
    voluptas ratione cumque dolorem autem nemo sequi earum voluptate reprehenderit
    molestias non optio enim dignissimos amet consequatur.
</p>

```

**Comment by Scotchester** [comment]
Isn't that covered by the `max-width` rule for paragraphs? (Did we actually
implement that, yet?)

**Comment by himedlooff** [comment]
We have not.

**Comment by Scotchester** [comment]
Re-appropriating this issue for discussion of adding a `max-wdith` rule for all paragraphs, which should go in this repo, if we adopt it.
