### ISSUE TITLE
Fix dumb formatting thing

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-core#31]
as seen here https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-utilities.less#L98

**Comment by anselmbradford** [comment]
@himedlooff Can you provide more context for this issue? Is it properties all on one line?

**Comment by himedlooff** [comment]
Yeah, needs line breaks.

**Comment by anselmbradford** [comment]
Thanks!
