### ISSUE TITLE
Set up self-hosted webfonts

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-core#33]
The code provided for using our webfont provider's CDN is not cutting it. We need to set up our fonts to be self-hosted. It's essentially a three-step process:
- [ ] Upload font files to a location on one of our servers
- [ ] Get access controls in place (to ensure fonts can only be accessed from approved hostnames)
- [ ] Update the `@font-face` code in this repo to refer to the new locations.

And then projects will need to update their version of cf-core to use the new self-hosted fonts.

/cc @poorgeek

**Comment by anselmbradford** [comment]
Not sure if this is relevant, but Cooper Hewitt has a repo for a font. Since it's a government entity, might be a helpful reference for licensing, etc. https://github.com/cooperhewitt/cooperhewitt-typeface

**Comment by Scotchester** [comment]
@anselmbradford That is pretty sweet! I didn't know they did so much open source work. Unfortunately, it's not relevant. They commissioned their own font that they are free to license as they choose. We are licensing an existing font, and are bound by the terms of that license.
