### ISSUE TITLE
Spin off IE-legacy component?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-core#40]
There are classes in cf-core that are only there for IE7- compatibility, such as https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-utilities.less#L115-L121. It might make sense to remove this clutter from the project and move it to a IE-legacy component that contains the IE7- tweaks, which could then be optionally imported if a project needed those hacks.

**Comment by himedlooff** [comment]
It might be cool to use https://github.com/cssdream/cssgrace for this legacy IE stuff. For example:

```
.bar {
  display: inline-block;
}
```

would become

```
.bar {
  display: inline-block;
  *display: inline;
  *zoom: 1;
}
```

But hmmmm, this would all be in the same stylesheet.

**Comment by jimmynotjim** [comment]
Post CSS FTW ;)
